apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service

# configure the way that this service behaves
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
      # ClusterIP이기에 NodePort가 들어가지 않음.