apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service

# configure the way that this service behaves
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432